### ISSUE TITLE
thenable weirdness?

### ISSUE THREAD

**Issue by hoseyjoe** [core-haxe/http#6]
So I have this function that runs fine...
```
var httpClient:HttpClient = new HttpClient();
httpClient.get('https://gitlab.com/api/v4/projects/${project.selectedItem.value}/milestones?state=active${withToken}').then(result -> {
	var milestones:Array<Milestone> = result.response.bodyAsJson;
	milestoneDP.dataSource = ArrayDataSource.fromArray(milestones);
	milestoneDP.selectedIndex=0;
	trace("result.response");
}, (error:HttpError) -> {
	trace(error.body);
});
````

I comment out trace("result.response");
```
var httpClient:HttpClient = new HttpClient();
httpClient.get('https://gitlab.com/api/v4/projects/${project.selectedItem.value}/milestones?state=active${withToken}').then(result -> {
	var milestones:Array<Milestone> = result.response.bodyAsJson;
	milestoneDP.dataSource = ArrayDataSource.fromArray(milestones);
	milestoneDP.selectedIndex=0;
	//trace("result.response");
}, (error:HttpError) -> {
	trace(error.body);
});
````
Line 34 is }, (error:HttpError) -> {
I get
src/MainView.hx:34: lines 34-36 : (error : http.HttpError) -> Void should be Null<thenshim.ThenableCallback<Dynamic, Int>>
src/MainView.hx:34: lines 34-36 : ... For optional function argument 'onRejected'

**Comment by ianharrigan** [comment]
Yeah, this is normal for promises, the last line in the then callback needs to be something that is returned from the promise (even if its never used), so "return null" will work fine. Im surprised it worked with trace though, since that is also a void function... 

FYI, you can also return other promises to chain, and _technically_ dont need the "return" (although i always use it since its clearer imo)
